/*
===============================================================================
Data Exploration (Key Metrics) and Magnitude Analysis
===============================================================================
Purpose:
	- To calculate aggregated metrics (e.g., totals, averages) for quick insights.
    - To identify overall trends or spot anomalies.
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

/*-----------------------------------------------------------------------------------
1) Generate a Report that shows all key metrics of the business
-----------------------------------------------------------------------------------*/
-- Find the Total Sales
SELECT 'Total Sales' AS measure, SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
-- Find the average selling price
SELECT 'Average Prcie' AS measure, AVG(price) AS measure_value FROM gold.fact_sales
UNION ALL
-- Find how many items are sold
SELECT 'Total Items Sold' AS measure, SUM(quantity) AS measure_value FROM gold.fact_sales
UNION ALL
-- Find the Total number of Orders
SELECT 'Total No. Orders' AS measure, COUNT(DISTINCT order_number) AS measure_value FROM gold.fact_sales
UNION ALL
-- Find the total number of products
SELECT 'Total No. Products' AS measure, COUNT(DISTINCT product_key) AS measure_value FROM gold.fact_sales 
UNION ALL
-- Find the total number of customers
SELECT 'Total No. Customers' AS measure, COUNT(DISTINCT customer_key) AS measure_value FROM gold.fact_sales 
UNION ALL
-- Find the total number of customers that has placed an order
SELECT 'Total No. Customers Placed Orders' AS measure, COUNT(DISTINCT customer_key) AS measure_value FROM gold.fact_sales;


/*-----------------------------------------------------------------------------------
2) Quantifying data for understanding data distribution across categories
-----------------------------------------------------------------------------------*/
-- Find total customers by countries
SELECT
	country,
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

-- Find total customers by gender
SELECT
	gender,
	COUNT(gender) AS total_amount
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_amount DESC

-- Find total products by category
SELECT
	category,
	COUNT(product_name) AS total_amount
FROM gold.dim_products
GROUP BY category
ORDER BY total_amount DESC

-- Find the average cost of each category
SELECT
	category,
	AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC

-- Find the total revenue generated by each category
SELECT TOP 5
	p.product_name,
	SUM(s.sales_amount) AS total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
ON s.product_key = p.product_key
GROUP BY p.product_name
ORDER BY total_revenue 

-- Find the total revenue generated by each customer
SELECT
	s.customer_key,
	c.first_name,
	c.last_name,
	SUM(s.sales_amount) AS total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP BY s.customer_key, c.first_name, c.last_name
ORDER BY total_revenue DESC

-- Find the distribution of sold items in each countries
SELECT
	c.country,
	SUM(s.quantity) AS total_sold_items
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
ON s.customer_key = c.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC
